from typing import Tuple, Union

__version__: str

def sha256(data: bytes) -> bytes: ...
def ige256_encrypt(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def ige256_decrypt(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def ige256_encrypt_inplace(data: bytearray, key: bytes, iv: bytes) -> None: ...
def ige256_decrypt_inplace(data: bytearray, key: bytes, iv: bytes) -> None: ...
def ctr256_encrypt(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def ctr256_decrypt(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def ctr256_encrypt_inplace(data: bytearray, key: bytes, iv: bytes) -> None: ...
def ctr256_decrypt_inplace(data: bytearray, key: bytes, iv: bytes) -> None: ...
def kdf(auth_key: bytes, msg_key: bytes, is_outgoing: bool) -> Tuple[bytes, bytes]: ...
def pack_message(auth_key: bytes, message: bytes, is_outgoing: bool) -> bytes: ...
def unpack_message(auth_key: bytes, encrypted_packet: bytes, is_outgoing: bool) -> bytes: ...
